"""Cross-language parity with the Flutter app's crypto.

The fixture is generated by the Dart implementation itself:

    dart run tool/export_crypto_vectors.dart > telegram-bot/tests/fixtures/dart_vectors.json

If either side drifts, these fail. That matters because both write the same
.maFile format and sign the same Steam requests — a mismatch would surface as
codes Steam silently rejects, or accounts that will not decrypt.
"""

from __future__ import annotations

import json
from pathlib import Path

import pytest

from steamguard import confirmation_hash, file_encryptor, mobile_signature
from steamguard.totp import generate_code

FIXTURE = Path(__file__).parent / "fixtures" / "dart_vectors.json"


@pytest.fixture(scope="module")
def vectors() -> dict:
    if not FIXTURE.exists():
        pytest.skip(f"{FIXTURE.name} missing — regenerate it from the Dart tool")
    return json.loads(FIXTURE.read_text("utf-8"))


def test_totp_matches_dart(vectors):
    secret = vectors["inputs"]["shared_secret"]

    for case in vectors["totp"]:
        assert generate_code(secret, case["time"]) == case["code"], (
            f"TOTP mismatch at t={case['time']}"
        )


def test_confirmation_hash_matches_dart(vectors):
    secret = vectors["inputs"]["identity_secret"]

    for case in vectors["confirmation_hash"]:
        actual = confirmation_hash.generate_for_time(
            secret, case["time"], case["tag"]
        )
        assert actual == case["hash"], (
            f"Hash mismatch for tag={case['tag']!r} t={case['time']}"
        )


def test_mobile_signature_matches_dart(vectors):
    secret = vectors["inputs"]["shared_secret"]

    for case in vectors["mobile_signature"]:
        actual = mobile_signature.generate_base64(
            shared_secret=secret,
            version=case["version"],
            client_id=case["client_id"],
            steam_id=case["steam_id"],
        )
        assert actual == case["signature"], (
            f"Signature mismatch for client_id={case['client_id']}"
        )


def test_python_decrypts_dart_ciphertext(vectors):
    """The app encrypts, the bot reads — the direction that matters on import."""
    for case in vectors["file_encryption"]:
        plaintext = file_encryptor.decrypt_data(
            case["password"], case["salt"], case["iv"], case["ciphertext"]
        )
        assert plaintext == case["plaintext"]


def test_python_produces_identical_ciphertext(vectors):
    """Same key, salt and IV must yield the same bytes on both sides."""
    for case in vectors["file_encryption"]:
        actual = file_encryptor.encrypt_data(
            case["password"], case["salt"], case["iv"], case["plaintext"]
        )
        assert actual == case["ciphertext"]
